import strings from '../localization/LocalizedStrings';

const getSettingActivities = () => {
  return [
    {
      id: 1,
      appname: strings.ads_step_0_appname,
      title: strings.ads_step_0_title,
      subtitle: strings.ads_step_0_subtitle,
      detail: strings.ads_step_0_detail,
      steps: strings.ads_step_0_steps,
      specialNote: strings.ads_step_0_specialNote,
      illustration: require('../assets/images/music.png'),
      adsSettingPaths: [
        {
          package: 'com.miui.player',
          activity: 'com.miui.player.phone.ui.MusicSettings',
        },
      ],
      iconBackgroundColor: '#FF2284',
      iconName: 'music',
      iconFamily: 'FontAwesome',
      hideButton: false,
    },
    {
      id: 2,
      appname: strings.ads_step_1_appname,
      title: strings.ads_step_1_title,
      subtitle: strings.ads_step_1_subtitle,
      detail: strings.ads_step_1_detail,
      steps: strings.ads_step_1_steps,
      specialNote: strings.ads_step_1_specialNote,
      adsSettingPaths: [
        {
          package: 'com.miui.videoplayer',
          activity: 'com.miui.video.onlinevideo.feature.setting.SettingActivity',
        },
        {
          package: 'com.miui.videoplayer',
          activity: 'com.miui.video.global.activity.SettingActivity',
        },
      ],

      illustration: require('../assets/images/videoplayer.png'),
      iconBackgroundColor: '#E83F63',
      iconName: 'play-circle',
      iconFamily: 'FontAwesome',
      hideButton: false,
    },
    {
      id: 3,
      appname: strings.ads_step_2_appname,
      title: strings.ads_step_2_title,
      subtitle: strings.ads_step_2_subtitle,
      detail: strings.ads_step_2_detail,
      steps: strings.ads_step_2_steps,
      specialNote: strings.ads_step_2_specialNote,
      adsSettingPaths: [
        {
          package: 'com.android.thememanager',
          activity: 'com.android.thememanager.ThemeResourceTabActivity',
        },
        {
          package: 'com.android.thememanager',
          activity: 'com.android.thememanager.activity.ThemeResourcesTabActivity',
        },
      ],
      illustration: require('../assets/images/themes.png'),
      iconBackgroundColor: '#009DCC',
      iconName: 'color-lens',
      iconFamily: 'MaterialIcons',
      hideButton: false,
    },
    {
      id: 4,
      appname: strings.ads_step_3_appname,
      title: strings.ads_step_3_title,
      subtitle: strings.ads_step_3_subtitle,
      detail: strings.ads_step_3_detail,
      steps: strings.ads_step_3_steps,
      specialNote: strings.ads_step_3_specialNote,
      adsSettingPaths: [
        {
          package: 'com.mi.android.globalFileexplorer',
          activity: 'com.android.fileexplorer.FileExplorerTabActivity',
        },
        {
          package: 'com.mi.android.globalFileexplorer',
          activity: 'com.android.fileexplorer.activity.SettingPreferenceActivity',
        },
      ],
      illustration: require('../assets/images/file-manager.png'),
      iconBackgroundColor: '#FCB536',
      iconName: 'folder',
      iconFamily: 'MaterialIcons',
      hideButton: false,
    },
    {
      id: 5,
      appname: strings.ads_step_4_appname,
      title: strings.ads_step_4_title,
      subtitle: strings.ads_step_4_subtitle,
      detail: strings.ads_step_4_detail,
      steps: strings.ads_step_4_steps,
      specialNote: strings.ads_step_4_specialNote,
      adsSettingPaths: [
        {
          package: 'com.android.browser',
          activity: 'com.android.browser.BrowserSettingsActivity',
        },
      ],
      illustration: require('../assets/images/browser.png'),
      iconBackgroundColor: '#2399E3',
      iconName: 'globe',
      iconFamily: 'FontAwesome',
      hideButton: false,
    },
    {
      id: 6,
      appname: strings.ads_step_5_appname,
      title: strings.ads_step_5_title,
      subtitle: strings.ads_step_5_subtitle,
      detail: strings.ads_step_5_detail,
      steps: strings.ads_step_5_steps,
      specialNote: strings.ads_step_5_specialNote,
      adsSettingPaths: [
        {
          package: 'com.android.providers.downloads.ui',
          activity: 'com.android.providers.downloads.ui.DownloadList',
        },
        {
          package: 'com.android.providers.downloads.ui',
          activity: 'com.android.providers.downloads.ui.activity.InterSettingActivity',
        },
      ],
      illustration: require('../assets/images/download.png'),
      iconBackgroundColor: '#FF6827',
      iconName: 'download',
      iconFamily: 'FontAwesome',
      hideButton: false,
    },
    {
      id: 7,
      appname: strings.ads_step_6_appname,
      title: strings.ads_step_6_title,
      subtitle: strings.ads_step_6_subtitle,
      detail: strings.ads_step_6_detail,
      steps: strings.ads_step_6_steps,
      specialNote: strings.ads_step_6_specialNote,
      adsSettingPaths: [
        {
          package: 'com.miui.securitycenter',
          activity: 'com.miui.securityscan.ui.settings.SettingsActivity',
        },
      ],
      illustration: require('../assets/images/security.png'),
      iconBackgroundColor: '#00D59D',
      iconName: 'security',
      iconFamily: 'MaterialIcons',
      hideButton: false,
    },
    {
      id: 8,
      appname: strings.ads_step_7_appname,
      title: strings.ads_step_7_title,
      subtitle: strings.ads_step_7_subtitle,
      detail: strings.ads_step_7_detail,
      steps: strings.ads_step_7_steps,
      specialNote: strings.ads_step_7_specialNote,
      adsSettingPaths: [
        {
          package: 'com.miui.cleanmaster',
          activity: 'com.miui.optimizecenter.settings.SettingsActivity',
        },
      ],
      illustration: require('../assets/images/cleaner.png'),
      iconBackgroundColor: '#E89736',
      iconName: 'trash',
      iconFamily: 'FontAwesome',
      hideButton: false,
    },
    {
      id: 9,
      appname: strings.ads_step_8_appname,
      title: strings.ads_step_8_title,
      subtitle: strings.ads_step_8_subtitle,
      detail: strings.ads_step_8_detail,
      steps: strings.ads_step_8_steps,
      specialNote: strings.ads_step_8_specialNote,
      adsSettingPaths: [
        {
          package: 'com.miui.securitycenter',
          activity: 'com.miui.securityscan.MainActivity',
        },
      ],
      illustration: require('../assets/images/applock.png'),
      iconBackgroundColor: '#00B17D',
      iconName: 'lock',
      iconFamily: 'FontAwesome',
      hideButton: false,
    },
    {
      id: 10,
      appname: strings.ads_step_9_appname,
      title: strings.ads_step_9_title,
      subtitle: strings.ads_step_9_subtitle,
      detail: strings.ads_step_9_detail,
      steps: strings.ads_step_9_steps,
      specialNote: strings.ads_step_9_specialNote,
      adsSettingPaths: [
        {
          package: 'com.miui.securitycenter',
          activity: 'com.miui.optimizemanage.OptimizemanageMainActivity',
        },
      ],
      illustration: require('../assets/images/boostspeed.png'),
      iconBackgroundColor: '#5062EC',
      iconName: 'speedometer',
      iconFamily: 'SimpleLineIcons',
      hideButton: false,
    },
    {
      id: 11,
      appname: strings.ads_step_10_appname,
      title: strings.ads_step_10_title,
      subtitle: strings.ads_step_10_subtitle,
      detail: strings.ads_step_10_detail,
      steps: strings.ads_step_10_steps,
      specialNote: strings.ads_step_10_specialNote,
      adsSettingPaths: [
        {
          package: 'com.miui.securitycenter',
          activity: 'com.miui.appmanager.AppManagerMainActivity',
        },
      ],
      illustration: require('../assets/images/manageapps.png'),
      iconBackgroundColor: '#FACE59',
      iconName: 'apps',
      iconFamily: 'MaterialIcons',
      hideButton: false,
    },
    {
      id: 12,
      appname: strings.ads_step_11_appname,
      title: strings.ads_step_11_title,
      subtitle: strings.ads_step_11_subtitle,
      detail: strings.ads_step_11_detail,
      steps: strings.ads_step_11_steps,
      specialNote: strings.ads_step_11_specialNote,
      adsSettingPaths: [
        {
          package: 'com.android.settings',
          activity: 'com.android.settings.MiuiSettings',
        },
      ],
      illustration: require('../assets/images/adware.png'),
      iconBackgroundColor: '#FF2781',
      iconName: 'android',
      iconFamily: 'MaterialIcons',
      hideButton: false,
    },
    {
      id: 13,
      appname: strings.ads_step_12_appname,
      title: strings.ads_step_12_title,
      subtitle: strings.ads_step_12_subtitle,
      detail: strings.ads_step_12_detail,
      steps: strings.ads_step_12_steps,
      specialNote: strings.ads_step_12_specialNote,
      adsSettingPaths: [
        {
          package: 'com.android.settings',
          activity: 'com.android.settings.ad.AdServiceSettings',
        },
      ],
      illustration: require('../assets/images/track-user.png'),
      iconBackgroundColor: '#5062EC',
      iconName: 'adversal',
      iconFamily: 'FontAwesome5Pro',
      hideButton: false,
    },
    {
      id: 14,
      appname: strings.ads_step_13_appname,
      title: strings.ads_step_13_title,
      subtitle: strings.ads_step_13_subtitle,
      detail: strings.ads_step_13_detail,
      steps: strings.ads_step_13_steps,
      specialNote: strings.ads_step_13_specialNote,
      adsSettingPaths: [
        {
          package: null,
          activity: null,
        },
      ],
      illustration: require('../assets/images/appfolder.png'),
      iconBackgroundColor: '#5E6883',
      iconName: 'apps',
      iconFamily: 'MaterialIcons',
      hideButton: true,
    },
    {
      id: 15,
      appname: strings.ads_step_14_appname,
      title: strings.ads_step_14_title,
      subtitle: strings.ads_step_14_subtitle,
      detail: strings.ads_step_14_detail,
      steps: strings.ads_step_14_steps,
      specialNote: strings.ads_step_14_specialNote,
      adsSettingPaths: [
        {
          package: 'com.miui.home',
          activity: 'com.miui.home.settings.MiuiHomeSettingActivity',
        },
      ],
      illustration: require('../assets/images/recents.png'),
      iconBackgroundColor: '#00659D',
      iconName: 'clear-all',
      iconFamily: 'MaterialIcons',
      hideButton: false,
    },
  ];
};

module.exports = {getSettingActivities};
