// ES6 module syntax
import LocalizedStrings from 'react-native-localization';

//Russian language is translated directly from english using https://apertium.org/index.eng.html?dir=eng-epo#translation website.
let strings = new LocalizedStrings({
  en: {
    ads_step_0_appname: 'Music',
    ads_step_0_title: 'Mi Music App',
    ads_step_0_subtitle: 'Mi Music Player is the MIUI native music player which is designed just for Mi Fans.',
    ads_step_0_detail: 'Mi Music Player is the MIUI native music player which is designed just for Mi Fans. With Mi Music, playing local songs will be much easier.',
    ads_step_0_steps: '1. Open the Mi Music app.\n2. Go to Music app Settings.\n3. Tap on Advanced Settings.\n4. Turn off Recommendations.',
    ads_step_0_specialNote: '',
    ads_step_1_appname: 'MI Video',
    ads_step_1_title: 'MI Video App',
    ads_step_1_subtitle: 'Mi Video Player is the MIUI native video player which is designed just for Mi Fans.',
    ads_step_1_detail: 'Mi Video Player is the MIUI native video player which is designed just for Mi Fans. With Mi Video, playing local videos will be much easier.',
    ads_step_1_steps: '1. Open the MI Video app.\n2. In Account tab Tap on Settings\n3. Turn off Recommendations.',
    ads_step_1_specialNote: '',
    ads_step_2_appname: 'Themes',
    ads_step_2_title: 'Themes App',
    ads_step_2_subtitle: 'Themes app is the MIUI native theming app which is designed just for Mi Fans.',
    ads_step_2_detail: 'Themes app is the MIUI native theming app which is designed just for Mi Fans.',
    ads_step_2_steps: '1. Open the Theme app.\n2. In last tab Tap on Settings\n3. Turn off Recommendations.',
    ads_step_2_specialNote: 'You have to manually find ads setting.',
    ads_step_3_appname: 'File Manager',
    ads_step_3_title: 'Mi File Manager app',
    ads_step_3_subtitle: 'Mi File Manager is a free, secure tool that helps you find file faster, manage files easily, and share them offline with others',
    ads_step_3_detail: 'Mi File Manager is a free, secure tool that helps you find file faster, manage files easily, and share them offline with others',
    ads_step_3_steps: '1. Open Mi File Manager app.\n2. Tap on three horizontal lines at the top corner of Mi File Explorer.\n3. Go to Settings and About.\n4. Turn off Recommendations.',
    ads_step_3_specialNote: 'You have to manually find ads setting.',
    ads_step_4_appname: 'Browser',
    ads_step_4_title: 'Mi Browser',
    ads_step_4_subtitle: 'Mi Browser is an app from the category browsing, whose license is free which is available in english',
    ads_step_4_detail: 'Mi Browser is an app from the category browsing, whose license is free which is available in english',
    ads_step_4_steps: '1. Open Mi Browser.\n2. Open MIUI Browser Settings.\n3. Go to Advanced > Top sites order. If Top sites order option is missing, then look ever option until you find the recommendations option.\n4. Turn off Receive recommendations.',
    ads_step_4_specialNote: '',
    ads_step_5_appname: 'Downloads',
    ads_step_5_title: 'Downloads App',
    ads_step_5_subtitle: 'Mi Downloads app is the MIUI native downloader which is designed just for Mi Fans.',
    ads_step_5_detail: 'Mi Downloads app is the MIUI native downloader which is designed just for Mi Fans.',
    ads_step_5_steps: '1. Open Downloads app.\n2. Tap on three dots at the top corner.\n3. Go to Settings.\n4. Turn off Show recommended content.',
    ads_step_5_specialNote: 'You have to manually find ads setting.',
    ads_step_6_appname: 'Security',
    ads_step_6_title: 'Security App',
    ads_step_6_subtitle: 'Mi Security app is default security app which is designed for Mi fans.',
    ads_step_6_detail: 'Mi Security app is default security app which is designed for Mi fans.',
    ads_step_6_steps: '1. Open Mi Security App.\n2. Tap on Settings Gear Icon in the top corner.\n3. Under Recommendations turn off Receive recommendations.',
    ads_step_6_specialNote: '',
    ads_step_7_appname: 'Security',
    ads_step_7_title: 'Cleaner app',
    ads_step_7_subtitle: 'Mi Security app is part of Mi security app which is designed for Mi fans.',
    ads_step_7_detail: 'Mi Security app is part of Mi security app which is designed for Mi fans.',
    ads_step_7_steps: '1. Open Mi Security app.\n2. Tap on the Settings icon in the top corner.\n3. Tap on Cleaner under Feature Settings.\n4. Turn off Receive recommendations.',
    ads_step_7_specialNote: '',
    ads_step_8_appname: 'Security',
    ads_step_8_title: 'App Lock',
    ads_step_8_subtitle: 'App Lock protect your app with password or fingerprint.',
    ads_step_8_detail: 'Applock is part of Mi security app which is designed for Mi fans.',
    ads_step_8_steps: '1. Open Mi Security app.\n2.Tap on the App Lock.\n3. Tap on the Settings icon in the top corner.\n3. Turn off Receive recommendations.',
    ads_step_8_specialNote: '',
    ads_step_9_appname: 'Security',
    ads_step_9_title: 'Boost Speed App',
    ads_step_9_subtitle: 'Boost Speed App is part of Mi security aap which is designed to clean memory cache.',
    ads_step_9_detail: 'Boost Speed App is part of Mi security aap which is designed to clean memory cache.',
    ads_step_9_steps: '1. Open Mi Security app.\n2.Tap on the Boost speed.\n3. Tap on the Settings icon in the top corner.\n4. Turn off Receive recommendations.',
    ads_step_9_specialNote: '',
    ads_step_10_appname: 'Security',
    ads_step_10_title: 'Manage Apps App',
    ads_step_10_subtitle: 'Manage Apps App is part of Mi security aap which is designed to uninstall apps.',
    ads_step_10_detail: 'Manage Apps App is part of Mi security aap which is designed to uninstall apps.',
    ads_step_10_steps: '1. Open Mi Security app.\n2.Tap on the Manage apps.\n3. Tap on the three dots and then tap on Settings icon in the top corner.\n4. Turn off Receive recommendations.',
    ads_step_10_specialNote: '',
    ads_step_11_appname: 'MSA app',
    ads_step_11_title: 'MSA app',
    ads_step_11_subtitle: 'MiuiDeamon is spyware fron Xiaomi. It collects a lot of your data and sends it to Xiaomi servers.',
    ads_step_11_detail: 'MiuiDeamon is spyware fron Xiaomi. It collects a lot of your data and sends it to Xiaomi servers. MSA is Xiaomi advertising app that shows ad notifications and is a security risk aswell',
    ads_step_11_steps: '1.Go to Settings\n2. Go to Additional settings\n3. Authorization and revocation \n4. Tap on MSA AND MiuiDeamon\n5. Revoke authorization',
    ads_step_11_specialNote: 'You have to manually find ads setting.',
    ads_step_12_appname: 'Setting',
    ads_step_12_title: 'Advertising Identifier',
    ads_step_12_subtitle: 'When the recommendations are off, youll still see the same quality of ads as when its on',
    ads_step_12_detail: `When the recommendations are off, you'll still see the same quality of ads as when its on, but they wont be basen on your behaviour data or your personal information.`,
    ads_step_12_steps: '1. Open Settings app.\n2. Go to Additional Settings > Privacy > Ad services.\n3. Turn off Personalized Ad Recommendation.',
    ads_step_12_specialNote: '',
    ads_step_13_appname: 'App Folder',
    ads_step_13_title: 'App Folder',
    ads_step_13_subtitle: 'Disable Promoted apps toggle. This has to be done to every folder...',
    ads_step_13_detail: 'Disable Promoted apps toggle. This has to be done to every folder.',
    ads_step_13_steps: '1. Tap on the folder in which you want to disable ads/ Promoted apps.\n2. Tap on Folder Name.\n3. Disable Promoted apps toggle. This has to be done to every folder on MIUI.',
    ads_step_13_specialNote: 'Only applicable to MIUI default launcher.\nYou have to manually find your folder.',
    ads_step_14_appname: 'Recent Apps',
    ads_step_14_title: 'Recent Apps',
    ads_step_14_subtitle: 'Disable suggestions from Homescreen & Recents menu.',
    ads_step_14_detail: 'Disable suggestions from Homescreen & Recents menu.',
    ads_step_14_steps: '1. Open System Setting\n2. Navigate to Home screen & Recents\n3. Turn off Show suggestions.',
    ads_step_14_specialNote: '',
    about_change_language: 'Change Language',
    about_rate_playstore: 'Rate app on Playstore',
    about_terms_service: 'Terms of service',
    about_privacy_policy: 'Privacy Policy',
    about_credits: 'Credits',
    about_copy_right_name: 'Gajjar Tejas',
    about_copy_right: 'Copyright 2020',
    about_github: 'Contribute on Github',
    ads_detail_app_not_available: 'Probably this application is not installed on your phone!',
    ads_detail_desc: 'Description',
    ads_detail_open: 'Open',
    ads_detail_settings: 'Settings',
    ads_detail_steps: 'Steps',
    navigator_screen_title_home: 'Home',
    navigator_screen_title_about: 'About',
    navigator_screen_title_detail: 'Detail',
    navigator_screen_title_language: 'Select Language',
    navigator_screen_title_theme: 'Select Theme',
    navigator_screen_title_license: 'License',
  },
  ru: {
    ads_step_0_appname: 'Muziko',
    ads_step_0_title: 'Mi Muziko App',
    ads_step_0_subtitle: 'Mi Muzika Ludisto estas la MIUI indiĝena muziko ludisto kiu estas desegnita nur por Mi Fervoruloj.',
    ads_step_0_detail: 'Mi Muzika Ludisto estas la MIUI indiĝena muziko ludisto kiu estas desegnita nur por Mi Fervoruloj. Kun Mi Muziko, ludanta lokajn kantojn estos multe da pli facila.',
    ads_step_0_steps: '1. Malfermas la Mi Muziko app.\n2. Iras al Muziko app Fiksoj.\n3. Frapeto sur Altnivelaj Fiksoj.\n4. Elŝaltas Rekomendojn.',
    ads_step_0_specialNote: '',
    ads_step_1_appname: 'MIa Video',
    ads_step_1_title: 'MIa Video App',
    ads_step_1_subtitle: 'Mi Videa Ludisto estas la MIUI indiĝena video ludisto kiu estas desegnita nur por Mi Fervoruloj.',
    ads_step_1_detail: 'Mi Videa Ludisto estas la MIUI indiĝena video ludisto kiu estas desegnita nur por Mi Fervoruloj. Kun Mi Video, ludanta lokajn videojn estos multe da pli facila.',
    ads_step_1_steps: '1. Malfermas la MIan Videon app.\n2. En Konta klapeto Frapeto sur Fiksoj\n3. Elŝaltas Rekomendojn.',
    ads_step_1_specialNote: '',
    ads_step_2_appname: 'Temaj',
    ads_step_2_title: 'Temoj App',
    ads_step_2_subtitle: 'Temoj app estas la MIUIa indiĝeno theming app kiu estas desegnita nur por Mi Fervoruloj.',
    ads_step_2_detail: 'Temoj app estas la MIUIa indiĝeno theming app kiu estas desegnita nur por Mi Fervoruloj.',
    ads_step_2_steps: '1. Malfermas la Temon app.\n2. En lasta klapeto Frapeto sur Fiksoj\n3. Elŝaltas Rekomendojn.',
    ads_step_2_specialNote: 'Vi mane devi trovi ads fikso.',
    ads_step_3_appname: 'Dosiera Manaĝero',
    ads_step_3_title: 'Mi Dosiera Manaĝero app',
    ads_step_3_subtitle: 'Mi Dosiera Manaĝero estas  libera, sekura ilo kiu helpas vin trovas dosieron pli rapida, administras dosierojn facile kaj dividi ilin elReta kun aliaj',
    ads_step_3_detail: 'Mi Dosiera Manaĝero estas  libera, sekura ilo kiu helpas vin trovas dosieron pli rapida, administras dosierojn facile kaj dividi ilin elReta kun aliaj',
    ads_step_3_steps: '1. Malferma Mi Dosiera Manaĝero app.\n2. Frapeto sur tri horizontalaj linioj ĉe la pinta angulo de Mi Dosiera Esploristo.\n3. Iras al Fiksoj kaj Proksimume.\n4. Elŝaltas Rekomendojn.',
    ads_step_3_specialNote: 'Vi mane devi trovi ads fikso.',
    ads_step_4_appname: 'Retumilo',
    ads_step_4_title: 'Mi Retumilo',
    ads_step_4_subtitle: 'Mi Retumilo estas  app de la kategorio foliumanta, kies licenco estas libera kiu estas havebla en english',
    ads_step_4_detail: 'Mi Retumilo estas  app de la kategorio foliumanta, kies licenco estas libera kiu estas havebla en english',
    ads_step_4_steps: '1. Malferma Mi Retumilo.\n2. Malferma MIUI Retumilaj Fiksoj.\n3. Iras al Altnivela > Supro eja ordo. Se Pintaj ejoj orda elekto mankas, tiame rigardi iam ajn elekto ĝis vi trovas la rekomendan elekton.\n4. Elŝaltas Ricevas rekomendojn.',
    ads_step_4_specialNote: '',
    ads_step_5_appname: 'Deŝutoj',
    ads_step_5_title: 'Elŝutas App',
    ads_step_5_subtitle: 'Mi Elŝutas app estas la MIUI indiĝena downloader kiu estas desegnita nur por Mi Fervoruloj.',
    ads_step_5_detail: 'Mi Elŝutas app estas la MIUI indiĝena downloader kiu estas desegnita nur por Mi Fervoruloj.',
    ads_step_5_steps: '1. Malfermaj Deŝutoj app.\n2. Frapeto sur tri punktoj ĉe la pinta angulo.\n3. Iras al Fiksoj.\n4. Elŝaltas Rezulton rekomendita enhavon.',
    ads_step_5_specialNote: 'Vi mane devi trovi ads fikso.',
    ads_step_6_appname: 'Sekureca',
    ads_step_6_title: 'Sekureco App',
    ads_step_6_subtitle: 'Mi Sekureco app estas defaŭlta sekureco app kiu estas desegnita por Mi fervoruloj.',
    ads_step_6_detail: 'Mi Sekureco app estas defaŭlta sekureco app kiu estas desegnita por Mi fervoruloj.',
    ads_step_6_steps: '1. Malferma Mi Sekureco App.\n2. Frapeto sur Fiksa Ilaro Ikono en la pinta angulo.\n3. Sub Rekomendoj elŝaltas Ricevas rekomendojn.',
    ads_step_6_specialNote: '',
    ads_step_7_appname: 'Sekureco',
    ads_step_7_title: 'Pli Pura app',
    ads_step_7_subtitle: 'Mi Sekureco app estas parto de Mi sekureco app kiu estas desegnita por Mi fervoruloj.',
    ads_step_7_detail: 'Mi Sekureco app estas parto de Mi sekureco app kiu estas desegnita por Mi fervoruloj.',
    ads_step_7_steps: '1. Malferma Mi Sekureco app.\n2. Frapeto sur la Fiksa ikono en la pinta angulo.\n3. Frapeto sur Pli Pura sub Ĉefaĵaj Fiksoj.\n4. Elŝaltas Ricevas rekomendojn.',
    ads_step_7_specialNote: '',
    ads_step_8_appname: 'Sekureco',
    ads_step_8_title: 'App Ŝlosiĝas',
    ads_step_8_subtitle: 'App Seruro protektas via app kun pasvorto aŭ fingrospuro.',
    ads_step_8_detail: 'Applock estas parto de Mi sekureco app kiu estas desegnita por Mi fervoruloj.',
    ads_step_8_steps: '1. Malferma Mi Sekureco app.\n2.Frapeto sur la App Seruro.\n3. Frapeto sur la Fiksa ikono en la pinta angulo.\n4. Elŝaltas Ricevas rekomendojn.',
    ads_step_8_specialNote: '',
    ads_step_9_appname: 'Sekureca',
    ads_step_9_title: 'Akcelo Rapidas App',
    ads_step_9_subtitle: 'Akcela Rapido App estas parto de Mi sekureco aap kiu estas desegnita purigadi memoran konservejon.',
    ads_step_9_detail: 'Akcela Rapido App estas parto de Mi sekureco aap kiu estas desegnita purigadi memoran konservejon.',
    ads_step_9_steps: '1. Malferma Mi Sekureco app.\n2.Frapeto sur la Akcela rapido.\n3. Frapeto sur la Fiksa ikono en la pinta angulo.\n4. Elŝaltas Ricevas rekomendojn.',
    ads_step_9_specialNote: '',
    ads_step_10_appname: 'Sekureco',
    ads_step_10_title: 'Administras Apps App',
    ads_step_10_subtitle: 'Administras Apps App estas parto de Mi sekureco aap kiu estas desegnita al uninstall apps.',
    ads_step_10_detail: 'Administras Apps App estas parto de Mi sekureco aap kiu estas desegnita al uninstall apps.',
    ads_step_10_steps: '1. Malferma Mi Sekureco app.\n2.Frapeto sur la Administri apps.\n3. Frapeto sur la tri punktoj kaj tiame frapeti sur Fiksa ikono en la pinta angulo.\n4. Elŝaltas Ricevas rekomendojn.',
    ads_step_10_specialNote: '',
    ads_step_11_appname: 'MSA app',
    ads_step_11_title: 'MSA app',
    ads_step_11_subtitle: 'MiuiDeamon estas spyware fron Xiaomi. Ĝi kolektas multa via datumo kaj sendas ĝin al Xiaomi serviloj.',
    ads_step_11_detail: 'MiuiDeamon estas spyware fron Xiaomi. Ĝi kolektas multa via datumo kaj sendas ĝin al Xiaomi serviloj. MSA estas Xiaomi reklamado app kiu montras ad sciigoj kaj estas sekureca risko aswell',
    ads_step_11_steps: '1.Iras al Fiksoj\n2. Iras al Suplementaj fiksoj\n3. Rajtigo kaj revocation \n4. Frapeto sur MSAa AND MiuiDeamon\n5. Revokas rajtigon',
    ads_step_11_specialNote: 'Vi mane devi trovi ads fikso.',
    ads_step_12_appname: 'Fiksanta',
    ads_step_12_title: 'Reklamadan Identigilon',
    ads_step_12_subtitle: 'Kiam la rekomendoj estas ekstere, youll ankoraŭ vidi la saman kvaliton de ads kiel kiam ties sur',
    ads_step_12_detail: `Kiam la rekomendoj estas ekstere, vi ankoraŭ vidos la saman kvaliton de ads kiel kiam ties sur, sed ili wont esti basen sur via konduta datumo aŭ via propra informo.`,
    ads_step_12_steps: '1. Malfermaj Fiksoj app.\n2. Iras al Suplementaj Fiksoj > Privateco > Ad servoj.\n3. Elŝaltas Personecigita Ad Rekomendo.',
    ads_step_12_specialNote: '',
    ads_step_13_appname: 'App Teko',
    ads_step_13_title: 'App Teko',
    ads_step_13_subtitle: 'Malfunkciigas Antaŭenigita apps toggle. Tio ĉi devas esti farita al ĉiu teko...',
    ads_step_13_detail: 'Malfunkciigas Antaŭenigita apps toggle. Tio ĉi devas esti farita al ĉiu teko.',
    ads_step_13_steps: '1. Frapeto sur la teko en kiu vi deziras malfunkciigi ads/ Antaŭenigis apps.\n2. Frapeto sur Teka Nomo.\n3. Malfunkciigas Antaŭenigita apps toggle. Tio ĉi devas esti farita al ĉiu teko sur MIUI.',
    ads_step_13_specialNote: 'Nur aplikebla al MIUI defaŭlta launcher.\nYou mane devi trovi vian tekon.',
    ads_step_14_appname: 'Lastatempa Apps',
    ads_step_14_title: 'Lastatempa Apps',
    ads_step_14_subtitle: 'Malfunkciigas sugestojn de Homescreen & Recents menuo.',
    ads_step_14_detail: 'Malfunkciigas sugestojn de Homescreen & Recents menuo.',
    ads_step_14_steps: '1. Malferma Sistemo Fiksanta\n2. Navigas al Hejma ekrano & Recents\n3. Elŝaltas Rezultajn sugestojn.',
    ads_step_14_specialNote: '',
    about_change_language: 'Ŝanĝa Lingvo',
    about_rate_playstore: 'Indico app sur Playstore',
    about_terms_service: 'Terminoj de serva',
    about_privacy_policy: 'Privateco Politiko',
    about_credits: 'Kreditas',
    about_copy_right_name: 'Gajjar Tejas',
    about_copy_right: 'Kopirajto 2020',
    about_github: 'Kontribuas sur Github',
    ads_detail_app_not_available: 'Verŝajne ĉi tiu apliko ne estas instalita sur via telefono!',
    ads_detail_desc: 'Priskriba',
    ads_detail_open: 'Turniro',
    ads_detail_settings: 'Fiksoj',
    ads_detail_steps: 'Paŝas',
    navigator_screen_title_home: 'Hejme',
    navigator_screen_title_about: 'Pri',
    navigator_screen_title_detail: 'Detalo',
    navigator_screen_title_language: 'Elektita Lingvo',
    navigator_screen_title_theme: 'Elektita Temo',
    navigator_screen_title_license: 'Licenco',
  },
});

export default strings;
